---
title: Panting Panda
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email:
description: This is the official site of Panting Panda.
baseurl:
url: https://pantingpanda.github.io
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
sass:
  sass_dir: _scss
  style: compressed
